//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exolutio.View.Commands {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CommandsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommandsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Exolutio.View.Commands.CommandsResources", typeof(CommandsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current project is not saved.
        /// </summary>
        internal static string guiCloseAppCommand_Execute_Current_project_is_not_saved {
            get {
                return ResourceManager.GetString("guiCloseAppCommand_Execute_Current_project_is_not_saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save it?.
        /// </summary>
        internal static string guiCloseAppCommand_Execute_Do_you_want_to_save_it_ {
            get {
                return ResourceManager.GetString("guiCloseAppCommand_Execute_Do_you_want_to_save_it_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closes eXolutio application.
        /// </summary>
        internal static string guiCloseAppCommand_ScreenTipText_Closes_Exolutio_application {
            get {
                return ResourceManager.GetString("guiCloseAppCommand_ScreenTipText_Closes_Exolutio_application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string guiCloseAppCommand_Text_Close {
            get {
                return ResourceManager.GetString("guiCloseAppCommand_Text_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current project is not saved.
        /// </summary>
        internal static string guiCloseProjectCommand_Execute_Current_project_is_not_saved {
            get {
                return ResourceManager.GetString("guiCloseProjectCommand_Execute_Current_project_is_not_saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save it?.
        /// </summary>
        internal static string guiCloseProjectCommand_Execute_Do_you_want_to_save_it_ {
            get {
                return ResourceManager.GetString("guiCloseProjectCommand_Execute_Do_you_want_to_save_it_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closes current project.
        /// </summary>
        internal static string guiCloseProjectCommand_ScreenTipText_Closes_current_project {
            get {
                return ResourceManager.GetString("guiCloseProjectCommand_ScreenTipText_Closes_current_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close project.
        /// </summary>
        internal static string guiCloseProjectCommand_Text_Close_project {
            get {
                return ResourceManager.GetString("guiCloseProjectCommand_Text_Close_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current project is not saved.
        /// </summary>
        internal static string guiNewProjectCommand_Execute_Current_project_is_not_saved {
            get {
                return ResourceManager.GetString("guiNewProjectCommand_Execute_Current_project_is_not_saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save it?.
        /// </summary>
        internal static string guiNewProjectCommand_Execute_Do_you_want_to_save_it_ {
            get {
                return ResourceManager.GetString("guiNewProjectCommand_Execute_Do_you_want_to_save_it_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new project.
        /// </summary>
        internal static string guiNewProjectCommand_Execute_new_project {
            get {
                return ResourceManager.GetString("guiNewProjectCommand_Execute_new_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates new empty eXolutio project.
        /// </summary>
        internal static string guiNewProjectCommand_ScreenTipText_Creates_new_empty_Exolutio_project {
            get {
                return ResourceManager.GetString("guiNewProjectCommand_ScreenTipText_Creates_new_empty_Exolutio_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New project.
        /// </summary>
        internal static string guiNewProjectCommand_Text_New_project {
            get {
                return ResourceManager.GetString("guiNewProjectCommand_Text_New_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .eXo.
        /// </summary>
        internal static string guiOpenProjectCommand_Execute_Exolutio_Default_Extension {
            get {
                return ResourceManager.GetString("guiOpenProjectCommand_Execute_Exolutio_Default_Extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eXo.
        /// </summary>
        internal static string guiOpenProjectCommand_Execute_Exolutio_Default_Extension_No_Dot {
            get {
                return ResourceManager.GetString("guiOpenProjectCommand_Execute_Exolutio_Default_Extension_No_Dot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eXolutio files (*.eXo)|*.eXo; *.evox|XML files (*.xml)|*.xml|All files (*.*)|*.*||.
        /// </summary>
        internal static string guiOpenProjectCommand_Execute_Exolutio_files____Exolutio____Exolutio_XML_files____xml____xml_All_files____________ {
            get {
                return ResourceManager.GetString("guiOpenProjectCommand_Execute_Exolutio_files____Exolutio____Exolutio_XML_files___" +
                        "_xml____xml_All_files____________", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens new eXolutio project.
        /// </summary>
        internal static string guiOpenProjectCommand_ScreenTipText_Opens_new_Exolutio_project {
            get {
                return ResourceManager.GetString("guiOpenProjectCommand_ScreenTipText_Opens_new_Exolutio_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open project.
        /// </summary>
        internal static string guiOpenProjectCommand_Text_Open_project {
            get {
                return ResourceManager.GetString("guiOpenProjectCommand_Text_Open_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saves eXolutio project under a given file name.
        /// </summary>
        internal static string guiSaveAsProjectCommand_ScreenTipText_Saves_Exolutio_project_under_a_given_file_name {
            get {
                return ResourceManager.GetString("guiSaveAsProjectCommand_ScreenTipText_Saves_Exolutio_project_under_a_given_file_n" +
                        "ame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as.
        /// </summary>
        internal static string guiSaveAsProjectCommand_Text_Save_as {
            get {
                return ResourceManager.GetString("guiSaveAsProjectCommand_Text_Save_as", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saves changes made in the project.
        /// </summary>
        internal static string guiSaveProjectCommand_ScreenTipText_Saves_changes_made_in_the_project {
            get {
                return ResourceManager.GetString("guiSaveProjectCommand_ScreenTipText_Saves_changes_made_in_the_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save project.
        /// </summary>
        internal static string guiSaveProjectCommand_Text_Save_project {
            get {
                return ResourceManager.GetString("guiSaveProjectCommand_Text_Save_project", resourceCulture);
            }
        }
    }
}
