//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exolutio.Model.PSM.Grammar.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Exolutio.Model.PSM.Grammar.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;&lt;!--*- XML -*--&gt;
        ///
        ///&lt;!-- +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ --&gt;
        ///&lt;!-- $Id: RngToRncClassic.xsl,v 1.1 2003/02/07 12:30:25 daro Exp $ --&gt;
        ///&lt;!-- +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ --&gt;
        ///
        ///&lt;!-- +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
        ///
        ///     Copyright (c) 2002, Pantor Engineering AB
        ///     All rights reserved.
        ///     
        ///     Redistribution and use in source and binary forms, with or
        ///     without modification, are permi [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RngToRncClassic {
            get {
                return ResourceManager.GetString("RngToRncClassic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- schemaVersion of 2001/02/15 --&gt;
        ///&lt;xs:schema targetNamespace=&quot;http://www.ascc.net/xml/schematron&quot; xmlns:sch=&quot;http://www.ascc.net/xml/schematron&quot; xmlns=&quot;http://www.ascc.net/xml/schematron&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; version=&quot;+//IDN sinica.edu.tw//SGML W3C XML Schema for Schematron 1.5//EN&quot;&gt;
        ///&lt;xs:import namespace=&quot;http://www.w3.org/XML/1998/namespace&quot; schemaLocation=&quot;http://www.w3.org/2001/xml.xsd&quot;&gt;
        ///&lt;xs:annotation&gt;
        ///&lt;xs:documentation&gt;
        /// Get access to the xml: attribute groups for xml:lan [rest of string was truncated]&quot;;.
        /// </summary>
        public static string schematronXSD {
            get {
                return ResourceManager.GetString("schematronXSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;xs:schema xmlns=&quot;http://www.ascc.net/xml/schematron&quot; xmlns:sch=&quot;http://www.ascc.net/xml/schematron&quot; 
        ///targetNamespace=&quot;http://www.ascc.net/xml/schematron&quot; version=&quot;+//IDN sinica.edu.tw//SGML W3C XML Schema for Schematron 1.5//EN&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  
        ///  &lt;!--
        ///  &lt;xs:import schemaLocation=&quot;http://www.w3.org/2001/xml.xsd&quot; namespace=&quot;http://www.w3.org/XML/1998/namespace&quot;&gt;
        ///    &lt;xs:annotation&gt;
        ///      &lt;xs:documentation&gt;
        /// Get access to the xml: [rest of string was truncated]&quot;;.
        /// </summary>
        public static string schematronXSDwithNamespace {
            get {
                return ResourceManager.GetString("schematronXSDwithNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;xs:schema xmlns=&quot;http://www.w3.org/1999/xhtml&quot; targetNamespace=&quot;http://www.w3.org/XML/1998/namespace&quot; xml:lang=&quot;en&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;xs:annotation&gt;
        ///    &lt;xs:documentation&gt;
        ///      &lt;div xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///        &lt;h1&gt;About the XML namespace&lt;/h1&gt;
        ///        &lt;div class=&quot;bodytext&quot;&gt;
        ///          &lt;p&gt;
        ///      This schema document describes the XML namespace, in a form
        ///      suitable for import by other schema documents.
        ///      [rest of string was truncated]&quot;;.
        /// </summary>
        public static string xmlNamespaceXSD {
            get {
                return ResourceManager.GetString("xmlNamespaceXSD", resourceCulture);
            }
        }
    }
}
