//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exolutio.Model.Serialization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SerializationLogMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SerializationLogMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Exolutio.Model.Serialization.SerializationLogMessages", typeof(SerializationLogMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection node {0} missing attribute &apos;Count&apos;..
        /// </summary>
        internal static string Collection_node__0__missing_attribute__Count__ {
            get {
                return ResourceManager.GetString("Collection_node__0__missing_attribute__Count__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection node {0} not found in node {1}..
        /// </summary>
        internal static string Collection_node__0__not_found_in_node__1__ {
            get {
                return ResourceManager.GetString("Collection_node__0__not_found_in_node__1__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value of attribute &apos;Count&apos; = {0} is different than the actual number of items in the collection node {1} (which is {2}).
        /// </summary>
        internal static string InconsistentCount {
            get {
                return ResourceManager.GetString("InconsistentCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenalezena trida v ClassifierContextHeader.
        /// </summary>
        internal static string OCLParser_ClassifierContextHead_Missing_Classifier_Header {
            get {
                return ResourceManager.GetString("OCLParser_ClassifierContextHead_Missing_Classifier_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On type `{0}` is not defined operation `{1}`..
        /// </summary>
        internal static string OCLParser_InfixOperation_InfixOperationNotFound_2 {
            get {
                return ResourceManager.GetString("OCLParser_InfixOperation_InfixOperationNotFound_2", resourceCulture);
            }
        }
    }
}
