//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exolutio.WPFClient.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Exolutio.WPFClient.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;DockingManager version=&quot;1.3.0&quot;&gt;
        ///    &lt;ResizingPanel ResizeWidth=&quot;*&quot; ResizeHeight=&quot;*&quot; EffectiveSize=&quot;0,0&quot; Orientation=&quot;Horizontal&quot;&gt;
        ///        &lt;DockablePane ResizeWidth=&quot;150&quot; ResizeHeight=&quot;*&quot; EffectiveSize=&quot;150,530&quot; ID=&quot;3113003d-57d4-4bbf-9dc1-6fa976640940&quot; Anchor=&quot;Left&quot; IsAutoHidden=&quot;false&quot;&gt;
        ///            &lt;DockableContent Name=&quot;navigatorTab&quot; FloatingWindowSize=&quot;250,400&quot; /&gt;
        ///        &lt;/DockablePane&gt;
        ///        &lt;ResizingPanel ResizeWidth=&quot;*&quot; ResizeHeight=&quot;*&quot; EffectiveSize=&quot;382,530&quot; Orientation=&quot;Vertical&quot;&gt;
        ///        [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string defaultLayout {
            get {
                return ResourceManager.GetString("defaultLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;SyntaxDefinition name=&quot;OCL&quot;
        ///        xmlns=&quot;http://icsharpcode.net/sharpdevelop/syntaxdefinition/2008&quot;&gt;
        ///  &lt;Color name=&quot;Comment&quot; foreground=&quot;Green&quot; /&gt;
        ///  &lt;Color name=&quot;String&quot; foreground=&quot;Blue&quot; /&gt;
        ///  &lt;Color name=&quot;Keywords&quot; fontWeight=&quot;bold&quot; foreground=&quot;Blue&quot; /&gt;
        ///  &lt;!-- This is the main ruleset. --&gt;
        ///  &lt;RuleSet&gt;
        ///    &lt;Span color=&quot;Comment&quot; begin=&quot;//&quot; /&gt;
        ///    &lt;Span color=&quot;Comment&quot; multiline=&quot;true&quot;
        ///       begin=&quot;/\*&quot; end=&quot;\*/&quot; /&gt;
        ///
        ///    &lt;Span color=&quot;String&quot;&gt;
        ///      &lt;Begin&gt;&quot;&lt;/Begin&gt;
        ///      &lt;End&gt;&quot;&lt;/End&gt;
        ///      &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OCL_syntax {
            get {
                return ResourceManager.GetString("OCL_syntax", resourceCulture);
            }
        }
    }
}
