//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvoX.Controller.Commands {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CommandReports {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommandReports() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EvoX.Controller.Commands.CommandReports", typeof(CommandReports).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cardinality of &apos;{0}&apos; changed from &apos;{1}&apos; to &apos;{2}&apos;..
        /// </summary>
        internal static string CARDINALITY_CHANGED {
            get {
                return ResourceManager.GetString("CARDINALITY_CHANGED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; was added to diagram &apos;{1}&apos;..
        /// </summary>
        internal static string COMPONENT_ADDED_TO_DIAGRAM {
            get {
                return ResourceManager.GetString("COMPONENT_ADDED_TO_DIAGRAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; moved from &apos;{1}&apos; to &apos;{2}&apos;..
        /// </summary>
        internal static string COMPONENT_MOVED {
            get {
                return ResourceManager.GetString("COMPONENT_MOVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; moved to roots of &apos;{1}&apos;..
        /// </summary>
        internal static string COMPONENT_MOVED_TO_ROOTS {
            get {
                return ResourceManager.GetString("COMPONENT_MOVED_TO_ROOTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; was removed from diagram &apos;{1}&apos;..
        /// </summary>
        internal static string COMPONENT_REMOVED_FROM_DIAGRAM {
            get {
                return ResourceManager.GetString("COMPONENT_REMOVED_FROM_DIAGRAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; removed from roots of &apos;{1}&apos;..
        /// </summary>
        internal static string COMPONENT_REMOVED_FROM_ROOTS {
            get {
                return ResourceManager.GetString("COMPONENT_REMOVED_FROM_ROOTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component &apos;{0}&apos; renamed from &apos;{1}&apos; to &apos;{2}&apos;..
        /// </summary>
        internal static string COMPONENT_RENAMED {
            get {
                return ResourceManager.GetString("COMPONENT_RENAMED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIM associations &apos;{0}&apos; synchronized with &apos;{1}&apos;.
        /// </summary>
        internal static string PIM_ASSOC_SYNCHRO {
            get {
                return ResourceManager.GetString("PIM_ASSOC_SYNCHRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIM attributes &apos;{0}&apos; synchronized with &apos;{1}&apos;.
        /// </summary>
        internal static string PIM_ATTR_SYNCHRO {
            get {
                return ResourceManager.GetString("PIM_ATTR_SYNCHRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; was added to the PIM. .
        /// </summary>
        internal static string PIM_component_added {
            get {
                return ResourceManager.GetString("PIM_component_added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; deleted from the PIM..
        /// </summary>
        internal static string PIM_component_deleted {
            get {
                return ResourceManager.GetString("PIM_component_deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project renamed from &apos;{0}&apos; to &apos;{1}&apos;..
        /// </summary>
        internal static string PROJECT_RENAMED {
            get {
                return ResourceManager.GetString("PROJECT_RENAMED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PSM associations &apos;{0}&apos; synchronized with &apos;{1}&apos;.
        /// </summary>
        internal static string PSM_ASSOC_SYNCHRO {
            get {
                return ResourceManager.GetString("PSM_ASSOC_SYNCHRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PSM attributes &apos;{0}&apos; synchronized with &apos;{1}&apos;.
        /// </summary>
        internal static string PSM_ATTR_SYNCHRO {
            get {
                return ResourceManager.GetString("PSM_ATTR_SYNCHRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; was added to the PSM..
        /// </summary>
        internal static string PSM_component_added {
            get {
                return ResourceManager.GetString("PSM_component_added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; deleted from the PSM..
        /// </summary>
        internal static string PSM_component_deleted {
            get {
                return ResourceManager.GetString("PSM_component_deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; was added to the PSM..
        /// </summary>
        internal static string PSM_diagram_added {
            get {
                return ResourceManager.GetString("PSM_diagram_added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; was removed from to the PSM..
        /// </summary>
        internal static string PSM_diagram_removed {
            get {
                return ResourceManager.GetString("PSM_diagram_removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PSMSchema &apos;{1}&apos; renamed from &apos;{0}&apos; to &apos;{1}&apos;..
        /// </summary>
        internal static string SCHEMA_RENAMED {
            get {
                return ResourceManager.GetString("SCHEMA_RENAMED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Structural representant &apos;{0}&apos; changed from &apos;{1}&apos; to &apos;{2}&apos;..
        /// </summary>
        internal static string STRUCTURAL_REPRESENTANT_CHANGED {
            get {
                return ResourceManager.GetString("STRUCTURAL_REPRESENTANT_CHANGED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of &apos;{0}&apos; changed from &apos;{1}&apos; to &apos;{2}&apos;..
        /// </summary>
        internal static string TYPED_CHANGED {
            get {
                return ResourceManager.GetString("TYPED_CHANGED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version &apos;{0}&apos; removed from project..
        /// </summary>
        internal static string VERSION_REMOVED {
            get {
                return ResourceManager.GetString("VERSION_REMOVED", resourceCulture);
            }
        }
    }
}
