//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exolutio.Controller.Commands {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CommandErrors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommandErrors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Exolutio.Controller.Commands.CommandErrors", typeof(CommandErrors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot set interpretation for a PSM association, whose child is not a PSM class..
        /// </summary>
        internal static string CMDERR_CANNOT_SET_INTERPRETATION_CHILD_NOT_CLASS {
            get {
                return ResourceManager.GetString("CMDERR_CANNOT_SET_INTERPRETATION_CHILD_NOT_CLASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot set interpretation for this PSM attribute. The PIM class of the suggested PIM attribute is not the same as the PIMClass which is an interpretation of the PSM attribute&apos;s context class. It is not its more general class either..
        /// </summary>
        internal static string CMDERR_CANNOT_SET_INTERPRETATION_CLASSES_DONT_MATCH {
            get {
                return ResourceManager.GetString("CMDERR_CANNOT_SET_INTERPRETATION_CLASSES_DONT_MATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot set interpretation. Child is not interpreted..
        /// </summary>
        internal static string CMDERR_CANNOT_SET_INTERPRETATION_CMDERR_CANNOT_SET_INTERPRETATION_CHILD_NOT_INTERPRETED {
            get {
                return ResourceManager.GetString("CMDERR_CANNOT_SET_INTERPRETATION_CMDERR_CANNOT_SET_INTERPRETATION_CHILD_NOT_INTER" +
                        "PRETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot set interpretation for this PSM component. It does not belong to any interpreted PSM classes context..
        /// </summary>
        internal static string CMDERR_CANNOT_SET_INTERPRETATION_NO_INTCLASS {
            get {
                return ResourceManager.GetString("CMDERR_CANNOT_SET_INTERPRETATION_NO_INTCLASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot synchronize attributes from different classes..
        /// </summary>
        internal static string CMDERR_CANNOT_SYNCHRO_ATTS_DIFFERENT_CLASSES {
            get {
                return ResourceManager.GetString("CMDERR_CANNOT_SYNCHRO_ATTS_DIFFERENT_CLASSES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot synchronize empty sets..
        /// </summary>
        internal static string CMDERR_CANNOT_SYNCHRO_EMPTY_SETS {
            get {
                return ResourceManager.GetString("CMDERR_CANNOT_SYNCHRO_EMPTY_SETS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PSM associations can be synchronized only if they all contain the same PSM class and their other PSM classes all have the same interpretation.
        /// </summary>
        internal static string CMDERR_CANNOT_SYNCHRO_PSM_ASSOC {
            get {
                return ResourceManager.GetString("CMDERR_CANNOT_SYNCHRO_PSM_ASSOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted class still has associations..
        /// </summary>
        internal static string CMDERR_CLASS_HAS_ASSOCIATIONS {
            get {
                return ResourceManager.GetString("CMDERR_CLASS_HAS_ASSOCIATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted class still has attributes..
        /// </summary>
        internal static string CMDERR_CLASS_HAS_ATTRIBUTES {
            get {
                return ResourceManager.GetString("CMDERR_CLASS_HAS_ATTRIBUTES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The PSM class has some representants..
        /// </summary>
        internal static string CMDERR_CLASS_IS_REPRESENTED {
            get {
                return ResourceManager.GetString("CMDERR_CLASS_IS_REPRESENTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class is not root..
        /// </summary>
        internal static string CMDERR_CLASS_NOT_ROOT {
            get {
                return ResourceManager.GetString("CMDERR_CLASS_NOT_ROOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content model is not root..
        /// </summary>
        internal static string CMDERR_CM_NOT_ROOT {
            get {
                return ResourceManager.GetString("CMDERR_CM_NOT_ROOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CommandNumber should be assigned only once..
        /// </summary>
        internal static string CMDERR_COMMAND_NUMBER_ALTERED {
            get {
                return ResourceManager.GetString("CMDERR_COMMAND_NUMBER_ALTERED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content model still has child associations..
        /// </summary>
        internal static string CMDERR_CONTENT_MODEL_NOT_EMPTY {
            get {
                return ResourceManager.GetString("CMDERR_CONTENT_MODEL_NOT_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content model is not a root..
        /// </summary>
        internal static string CMDERR_CONTENT_MODEL_NOT_ROOT {
            get {
                return ResourceManager.GetString("CMDERR_CONTENT_MODEL_NOT_ROOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The generalization relations cannot form a cycle..
        /// </summary>
        internal static string CMDERR_CYCLIC_INHERITANCE {
            get {
                return ResourceManager.GetString("CMDERR_CYCLIC_INHERITANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cyclic representation would occur..
        /// </summary>
        internal static string CMDERR_CYCLIC_REPR {
            get {
                return ResourceManager.GetString("CMDERR_CYCLIC_REPR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot make class a general class because it is final..
        /// </summary>
        internal static string CMDERR_GENERAL_IS_FINAL {
            get {
                return ResourceManager.GetString("CMDERR_GENERAL_IS_FINAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type mismatch in CanExecute().
        /// </summary>
        internal static string CMDERR_INPUT_TYPE_MISMATCH {
            get {
                return ResourceManager.GetString("CMDERR_INPUT_TYPE_MISMATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command &quot;{0}&quot; was not correctly initialized, field &quot;{1}&quot; must be defined before execution..
        /// </summary>
        internal static string CMDERR_MANDATORY_ARGUMENT_NOT_INITIALIZED_2 {
            get {
                return ResourceManager.GetString("CMDERR_MANDATORY_ARGUMENT_NOT_INITIALIZED_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no common ancestor association member..
        /// </summary>
        internal static string CMDERR_NO_COMMON_ANCESTOR_ASSOC_MEMBER {
            get {
                return ResourceManager.GetString("CMDERR_NO_COMMON_ANCESTOR_ASSOC_MEMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no common ancestor class..
        /// </summary>
        internal static string CMDERR_NO_COMMON_ANCESTOR_CLASS {
            get {
                return ResourceManager.GetString("CMDERR_NO_COMMON_ANCESTOR_CLASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The source and the target class are not connected by an association..
        /// </summary>
        internal static string CMDERR_NO_COMMON_ASSOCIATION {
            get {
                return ResourceManager.GetString("CMDERR_NO_COMMON_ASSOCIATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The source and the target association members are not connected by an association, neither is one a structural representant of the other..
        /// </summary>
        internal static string CMDERR_NO_COMMON_ASSOCIATION_OR_REPR {
            get {
                return ResourceManager.GetString("CMDERR_NO_COMMON_ASSOCIATION_OR_REPR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The source and the target PSM classes&apos; interpretations are not connected by the suggested association..
        /// </summary>
        internal static string CMDERR_NO_COMMON_INTERPRETED_ASSOCIATION {
            get {
                return ResourceManager.GetString("CMDERR_NO_COMMON_INTERPRETED_ASSOCIATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specific class already has a general class. Multiple inheritance is not allowed..
        /// </summary>
        internal static string CMDERR_NO_MULTIPLE_INHERITANCE {
            get {
                return ResourceManager.GetString("CMDERR_NO_MULTIPLE_INHERITANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The general class must be different from the specific class..
        /// </summary>
        internal static string CMDERR_NO_SELF_INHERITANCE {
            get {
                return ResourceManager.GetString("CMDERR_NO_SELF_INHERITANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The two classes do not have the same interpretation..
        /// </summary>
        internal static string CMDERR_NOT_SAME_INTERPRETATION {
            get {
                return ResourceManager.GetString("CMDERR_NOT_SAME_INTERPRETATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create association. The child already has a parent association..
        /// </summary>
        internal static string CMDERR_PARENT_ASSOCIATION_EXISTS {
            get {
                return ResourceManager.GetString("CMDERR_PARENT_ASSOCIATION_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Represented class has different interpreted context than representant class.
        /// </summary>
        internal static string CMDERR_REPR_DIFFERENT_CONTEXT {
            get {
                return ResourceManager.GetString("CMDERR_REPR_DIFFERENT_CONTEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Represented class cannot be a PSM schema class..
        /// </summary>
        internal static string CMDERR_REPRESENTED_CANNOT_BE_SCHEMACLASS {
            get {
                return ResourceManager.GetString("CMDERR_REPRESENTED_CANNOT_BE_SCHEMACLASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result attribute &quot;{0}&quot; was not set during execution of the command {1}..
        /// </summary>
        internal static string CMDERR_RESULT_ARGUMENT_NULL {
            get {
                return ResourceManager.GetString("CMDERR_RESULT_ARGUMENT_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some roots still present..
        /// </summary>
        internal static string CMDERR_ROOTS_PRESENT {
            get {
                return ResourceManager.GetString("CMDERR_ROOTS_PRESENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PSM schema class cannot have interpretation..
        /// </summary>
        internal static string CMDERR_SCHEMACLASS_CANNOT_BE_INTERPRETED {
            get {
                return ResourceManager.GetString("CMDERR_SCHEMACLASS_CANNOT_BE_INTERPRETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in command stack consistency..
        /// </summary>
        internal static string CMDERR_STACK_INCONSISTENT {
            get {
                return ResourceManager.GetString("CMDERR_STACK_INCONSISTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One of the synchronized sets of associations is not a subset of associations between the two PIM classes connected by some of the associations.
        /// </summary>
        internal static string CMDERR_SYNCHRO_PIM_ASSOC_NOT_SUBSET {
            get {
                return ResourceManager.GetString("CMDERR_SYNCHRO_PIM_ASSOC_NOT_SUBSET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some parent PSM associations of uninterpreted subclasses of the PSM component have interpretation..
        /// </summary>
        internal static string CMDERR_UNINTERPRETED_SUBCLASS_ASSOCIATIONS_INTERPRETED {
            get {
                return ResourceManager.GetString("CMDERR_UNINTERPRETED_SUBCLASS_ASSOCIATIONS_INTERPRETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some PSM attributes within uninterpreted subclasses of the PSM component have interpretation..
        /// </summary>
        internal static string CMDERR_UNINTERPRETED_SUBCLASS_ATTRIBUTES_INTERPRETED {
            get {
                return ResourceManager.GetString("CMDERR_UNINTERPRETED_SUBCLASS_ATTRIBUTES_INTERPRETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command cannot be executed..
        /// </summary>
        internal static string COMMAND_CANT_EXECUTE {
            get {
                return ResourceManager.GetString("COMMAND_CANT_EXECUTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error: Propagation command could not be executed. Model now may be broken. Do not save the project and restart eXolutio..
        /// </summary>
        internal static string COMMAND_CANT_EXECUTE_PROPAGATION {
            get {
                return ResourceManager.GetString("COMMAND_CANT_EXECUTE_PROPAGATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error: Command could not be executed. Model now may be broken. Do not save the project and restart eXolutio..
        /// </summary>
        internal static string COMMAND_CANT_EXECUTE_UNEXPECTED {
            get {
                return ResourceManager.GetString("COMMAND_CANT_EXECUTE_UNEXPECTED", resourceCulture);
            }
        }
    }
}
