//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exolutio.Model.OCL {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CompilerErrors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CompilerErrors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Exolutio.Model.OCL.CompilerErrors", typeof(CompilerErrors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation {0}.{1} is ambiguous..
        /// </summary>
        internal static string AmbiguousNavigation {
            get {
                return ResourceManager.GetString("AmbiguousNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenalezena trida v ClassifierContextHeader.
        /// </summary>
        internal static string OCLAst_ClassifierContextHead_Nenalezena_trida_v_ClassifierContextHeader {
            get {
                return ResourceManager.GetString("OCLAst_ClassifierContextHead_Nenalezena_trida_v_ClassifierContextHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ‘Collection’ is an abstract class on the M1 level and has no M0 instances..
        /// </summary>
        internal static string OCLAst_CollectionLiteralExp_CollectionIsAbstract {
            get {
                return ResourceManager.GetString("OCLAst_CollectionLiteralExp_CollectionIsAbstract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrects mishmash type in collection literal..
        /// </summary>
        internal static string OCLAst_CollectionLiteralExp_Incorrects_mishmash_type_in_collection_literal {
            get {
                return ResourceManager.GetString("OCLAst_CollectionLiteralExp_Incorrects_mishmash_type_in_collection_literal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition of IF must conform to bool..
        /// </summary>
        internal static string OCLAst_CreateIf_Condition_of_IF_must_conform_to_bool {
            get {
                return ResourceManager.GetString("OCLAst_CreateIf_Condition_of_IF_must_conform_to_bool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad format of integer..
        /// </summary>
        internal static string OCLAst_CreateIntegerLiteral_Bad_format_of_integer {
            get {
                return ResourceManager.GetString("OCLAst_CreateIntegerLiteral_Bad_format_of_integer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number {0} is overflow..
        /// </summary>
        internal static string OCLAst_CreateIntegerLiteral_Number__0__is_overflow_ {
            get {
                return ResourceManager.GetString("OCLAst_CreateIntegerLiteral_Number__0__is_overflow_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad format of real..
        /// </summary>
        internal static string OCLAst_CreateRealLiteral_Bad_format_of_real {
            get {
                return ResourceManager.GetString("OCLAst_CreateRealLiteral_Bad_format_of_real", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name {0} is used multipled..
        /// </summary>
        internal static string OCLAst_CreateTupleLiteral_Name__0__is_used_multipled {
            get {
                return ResourceManager.GetString("OCLAst_CreateTupleLiteral_Name__0__is_used_multipled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type does not comform to declared type..
        /// </summary>
        internal static string OCLAst_CreateTupleLiteral_Type_does_not_comform_to_declared_type {
            get {
                return ResourceManager.GetString("OCLAst_CreateTupleLiteral_Type_does_not_comform_to_declared_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On type `{0}` is not defined operation `{1}`..
        /// </summary>
        internal static string OCLAst_InfixOperation_NotDefined {
            get {
                return ResourceManager.GetString("OCLAst_InfixOperation_NotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The variable name must be unique in the current scope.
        /// </summary>
        internal static string OCLAst_LetDecl_The_variable_name_must_be_unique_in_the_current_scope {
            get {
                return ResourceManager.GetString("OCLAst_LetDecl_The_variable_name_must_be_unique_in_the_current_scope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable type does not conform to variable expression type..
        /// </summary>
        internal static string OCLAst_LetDecl_Variable_type_does_not_conform_to_variable_expression_type {
            get {
                return ResourceManager.GetString("OCLAst_LetDecl_Variable_type_does_not_conform_to_variable_expression_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Init value do not conform to variable type..
        /// </summary>
        internal static string OCLAst_ProcessAccDef_Init_value_do_not_conform_to_variable_type {
            get {
                return ResourceManager.GetString("OCLAst_ProcessAccDef_Init_value_do_not_conform_to_variable_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown collection operation - {0}.
        /// </summary>
        internal static string OCLAst_ProcessCollectionOperationCall_Unknown_collection_operation {
            get {
                return ResourceManager.GetString("OCLAst_ProcessCollectionOperationCall_Unknown_collection_operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad iterator operation..
        /// </summary>
        internal static string OCLAst_ProcessIteratorCall_Bad_iterator_operation {
            get {
                return ResourceManager.GetString("OCLAst_ProcessIteratorCall_Bad_iterator_operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compiler don&apos;t support iterator operations on not-collection type..
        /// </summary>
        internal static string OCLAst_ProcessIteratorCall_Compiler_don_t_support_iterator_operations_on_not_collection_type {
            get {
                return ResourceManager.GetString("OCLAst_ProcessIteratorCall_Compiler_don_t_support_iterator_operations_on_not_coll" +
                        "ection_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iterator ma jenom jedno tělo výrazu..
        /// </summary>
        internal static string OCLAst_ProcessIteratorCall_Iterator_ma_jenom_jedno_tělo_výrazu {
            get {
                return ResourceManager.GetString("OCLAst_ProcessIteratorCall_Iterator_ma_jenom_jedno_tělo_výrazu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nesedi typy v body.
        /// </summary>
        internal static string OCLAst_ProcessIteratorCall_Nesedi_typy_v_body {
            get {
                return ResourceManager.GetString("OCLAst_ProcessIteratorCall_Nesedi_typy_v_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknow iterator operation..
        /// </summary>
        internal static string OCLAst_ProcessIteratorCall_Unknow_iterator_operation {
            get {
                return ResourceManager.GetString("OCLAst_ProcessIteratorCall_Unknow_iterator_operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation `{0}` does not exit..
        /// </summary>
        internal static string OCLAst_ProcessOperationCall_OperationNotExists {
            get {
                return ResourceManager.GetString("OCLAst_ProcessOperationCall_OperationNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property `{0}` does not exit..
        /// </summary>
        internal static string OCLAst_ProcessPropertyCall_PropertyNotExists {
            get {
                return ResourceManager.GetString("OCLAst_ProcessPropertyCall_PropertyNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operace `{0}` nenalezena..
        /// </summary>
        internal static string OCLAst_ResolveImplicitOperation {
            get {
                return ResourceManager.GetString("OCLAst_ResolveImplicitOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operace `{0}` nenalezena..
        /// </summary>
        internal static string OCLAst_ResolveImplicitOperation_OperaceNenalezena {
            get {
                return ResourceManager.GetString("OCLAst_ResolveImplicitOperation_OperaceNenalezena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chyba nebo nepodporovane pravidlo.
        /// </summary>
        internal static string OCLAst_ResolvePath_Chyba_nebo_nepodporovane_pravidlo {
            get {
                return ResourceManager.GetString("OCLAst_ResolvePath_Chyba_nebo_nepodporovane_pravidlo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifikator @pre se nepojí s proměnou.
        /// </summary>
        internal static string OCLAst_ResolvePath_Modifikator__pre_se_nepoji_s_promenou {
            get {
                return ResourceManager.GetString("OCLAst_ResolvePath_Modifikator__pre_se_nepoji_s_promenou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifikator @pre se nepojí s proměnou.
        /// </summary>
        internal static string OCLAst_ResolvePath_Modifikator__pre_se_nepojí_s_proměnou {
            get {
                return ResourceManager.GetString("OCLAst_ResolvePath_Modifikator__pre_se_nepojí_s_proměnou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path {0} do not exists..
        /// </summary>
        internal static string OCLAst_ResolveTypePathName_Path__0__do_not_exists {
            get {
                return ResourceManager.GetString("OCLAst_ResolveTypePathName_Path__0__do_not_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path {0} do not referres type..
        /// </summary>
        internal static string OCLAst_ResolveTypePathName_Path__0__do_not_referres_type {
            get {
                return ResourceManager.GetString("OCLAst_ResolveTypePathName_Path__0__do_not_referres_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compiler panic in method {0}..
        /// </summary>
        internal static string OCLAst_TestNull_Compiler_panic_in_method__0__ {
            get {
                return ResourceManager.GetString("OCLAst_TestNull_Compiler_panic_in_method__0__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable name `{0}` has already existed..
        /// </summary>
        internal static string VariableAlreadyExisted {
            get {
                return ResourceManager.GetString("VariableAlreadyExisted", resourceCulture);
            }
        }
    }
}
