//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exolutio.Model.OCL {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CompilerErrors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CompilerErrors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Exolutio.Model.OCL.CompilerErrors", typeof(CompilerErrors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation `{0}.{1}` is ambiguous..
        /// </summary>
        internal static string AmbiguousNavigation {
            get {
                return ResourceManager.GetString("AmbiguousNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classifier `{0}` (used in context header) not found..
        /// </summary>
        internal static string OCLAst_ClassifierContextHead_ClassifierNotFound_1 {
            get {
                return ResourceManager.GetString("OCLAst_ClassifierContextHead_ClassifierNotFound_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Collection&apos; is an abstract class, can not create instances. .
        /// </summary>
        internal static string OCLAst_CollectionLiteralExp_CollectionIsAbstract {
            get {
                return ResourceManager.GetString("OCLAst_CollectionLiteralExp_CollectionIsAbstract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inconsistent types in collection literal. .
        /// </summary>
        internal static string OCLAst_CollectionLiteralExp_Incorrects_mishmash_type_in_collection_literal {
            get {
                return ResourceManager.GetString("OCLAst_CollectionLiteralExp_Incorrects_mishmash_type_in_collection_literal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition in an if expression must be of type bool..
        /// </summary>
        internal static string OCLAst_CreateIf_Condition_of_IF_must_conform_to_bool {
            get {
                return ResourceManager.GetString("OCLAst_CreateIf_Condition_of_IF_must_conform_to_bool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong integer fromat. .
        /// </summary>
        internal static string OCLAst_CreateIntegerLiteral_Bad_format_of_integer {
            get {
                return ResourceManager.GetString("OCLAst_CreateIntegerLiteral_Bad_format_of_integer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Literal `{0}` results in overflow..
        /// </summary>
        internal static string OCLAst_CreateIntegerLiteral_Number__0__is_overflow_ {
            get {
                return ResourceManager.GetString("OCLAst_CreateIntegerLiteral_Number__0__is_overflow_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong real format.
        /// </summary>
        internal static string OCLAst_CreateRealLiteral_Bad_format_of_real {
            get {
                return ResourceManager.GetString("OCLAst_CreateRealLiteral_Bad_format_of_real", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name `{0}` is used repeatedly..
        /// </summary>
        internal static string OCLAst_CreateTupleLiteral_Name_repeated_1 {
            get {
                return ResourceManager.GetString("OCLAst_CreateTupleLiteral_Name_repeated_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type does not comform to the declared type..
        /// </summary>
        internal static string OCLAst_CreateTupleLiteral_Type_does_not_comform_to_declared_type {
            get {
                return ResourceManager.GetString("OCLAst_CreateTupleLiteral_Type_does_not_comform_to_declared_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infix operation `{1}` is not defined on type `{0}`..
        /// </summary>
        internal static string OCLAst_InfixOperation_NotDefined_2 {
            get {
                return ResourceManager.GetString("OCLAst_InfixOperation_NotDefined_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The variable name must be unique in the current scope..
        /// </summary>
        internal static string OCLAst_LetDecl_The_variable_name_must_be_unique_in_the_current_scope {
            get {
                return ResourceManager.GetString("OCLAst_LetDecl_The_variable_name_must_be_unique_in_the_current_scope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declared variable type does not conform to expression type..
        /// </summary>
        internal static string OCLAst_LetDecl_Variable_type_does_not_conform_to_variable_expression_type {
            get {
                return ResourceManager.GetString("OCLAst_LetDecl_Variable_type_does_not_conform_to_variable_expression_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value does not conform to variable type..
        /// </summary>
        internal static string OCLAst_ProcessAccDef_Init_value_do_not_conform_to_variable_type {
            get {
                return ResourceManager.GetString("OCLAst_ProcessAccDef_Init_value_do_not_conform_to_variable_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown collection operation `{0}`..
        /// </summary>
        internal static string OCLAst_ProcessCollectionOperationCall_Unknown_collection_operation {
            get {
                return ResourceManager.GetString("OCLAst_ProcessCollectionOperationCall_Unknown_collection_operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown iterator operation `{0}`. .
        /// </summary>
        internal static string OCLAst_ProcessIteratorCall_Bad_iterator_operation_1 {
            get {
                return ResourceManager.GetString("OCLAst_ProcessIteratorCall_Bad_iterator_operation_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inconsistent types in iterator body..
        /// </summary>
        internal static string OCLAst_ProcessIteratorCall_Body_type_inconsistency {
            get {
                return ResourceManager.GetString("OCLAst_ProcessIteratorCall_Body_type_inconsistency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compiler doesn&apos;t support iterator operations on non-collection type..
        /// </summary>
        internal static string OCLAst_ProcessIteratorCall_Compiler_don_t_support_iterator_operations_on_not_collection_type {
            get {
                return ResourceManager.GetString("OCLAst_ProcessIteratorCall_Compiler_don_t_support_iterator_operations_on_not_coll" +
                        "ection_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iterator must have only on body expression. .
        /// </summary>
        internal static string OCLAst_ProcessIteratorCall_Iterator_ma_jenom_jedno_tělo_výrazu {
            get {
                return ResourceManager.GetString("OCLAst_ProcessIteratorCall_Iterator_ma_jenom_jedno_tělo_výrazu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknow iterator operation..
        /// </summary>
        internal static string OCLAst_ProcessIteratorCall_Unknow_iterator_operation {
            get {
                return ResourceManager.GetString("OCLAst_ProcessIteratorCall_Unknow_iterator_operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknowon operation `{0}`..
        /// </summary>
        internal static string OCLAst_ProcessOperationCall_OperationNotExists_1 {
            get {
                return ResourceManager.GetString("OCLAst_ProcessOperationCall_OperationNotExists_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown property `{0}`..
        /// </summary>
        internal static string OCLAst_ProcessPropertyCall_PropertyNotExists_1 {
            get {
                return ResourceManager.GetString("OCLAst_ProcessPropertyCall_PropertyNotExists_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect context declaration: `{0}`. Class and operation name expected..
        /// </summary>
        internal static string OCLAst_PropertyContextHead_Incorrect_context_declaration___0___Class_and_operation_name_expected_1 {
            get {
                return ResourceManager.GetString("OCLAst_PropertyContextHead_Incorrect_context_declaration___0___Class_and_operatio" +
                        "n_name_expected_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property `{0}` of class `{1}` does not exist..
        /// </summary>
        internal static string OCLAst_PropertyContextHead_PropertyNotFound_2 {
            get {
                return ResourceManager.GetString("OCLAst_PropertyContextHead_PropertyNotFound_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of property `{0}` is `{1}`, but the initialization header states `{2}`..
        /// </summary>
        internal static string OCLAst_PropertyContextHead_TypeMismatch_3 {
            get {
                return ResourceManager.GetString("OCLAst_PropertyContextHead_TypeMismatch_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown operation `{0}`..
        /// </summary>
        internal static string OCLAst_ResolveImplicitOperation_1 {
            get {
                return ResourceManager.GetString("OCLAst_ResolveImplicitOperation_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown operation `{0}`..
        /// </summary>
        internal static string OCLAst_ResolveImplicitOperation_Operation_not_found_1 {
            get {
                return ResourceManager.GetString("OCLAst_ResolveImplicitOperation_Operation_not_found_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax error or unsupported syntax rule. .
        /// </summary>
        internal static string OCLAst_ResolvePath_Chyba_nebo_nepodporovane_pravidlo {
            get {
                return ResourceManager.GetString("OCLAst_ResolvePath_Chyba_nebo_nepodporovane_pravidlo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier `@pre` is not attached to a variable. .
        /// </summary>
        internal static string OCLAst_ResolvePath_Modifikator__pre_se_nepoji_s_promenou {
            get {
                return ResourceManager.GetString("OCLAst_ResolvePath_Modifikator__pre_se_nepoji_s_promenou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path `{0}` does not exist..
        /// </summary>
        internal static string OCLAst_ResolveTypePathName_Path__0__do_not_exists_1 {
            get {
                return ResourceManager.GetString("OCLAst_ResolveTypePathName_Path__0__do_not_exists_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path `{0}` does not refer a type..
        /// </summary>
        internal static string OCLAst_ResolveTypePathName_Path__0__do_not_referres_type_1 {
            get {
                return ResourceManager.GetString("OCLAst_ResolveTypePathName_Path__0__do_not_referres_type_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compiler panic in method `{0}`..
        /// </summary>
        internal static string OCLAst_TestNull_Compiler_panic_in_method_1 {
            get {
                return ResourceManager.GetString("OCLAst_TestNull_Compiler_panic_in_method_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ‘Collection’ is an abstract class and can not be instantiated. .
        /// </summary>
        internal static string OCLParser_CollectionLiteralExpAndType_Attemt_to_instantiate_abstract_type {
            get {
                return ResourceManager.GetString("OCLParser_CollectionLiteralExpAndType_Attemt_to_instantiate_abstract_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inconsistent types in collection literal. .
        /// </summary>
        internal static string OCLParser_CollectionLiteralExpAndType_Inconsistent_types_in_collection_literal {
            get {
                return ResourceManager.GetString("OCLParser_CollectionLiteralExpAndType_Inconsistent_types_in_collection_literal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wront integer format. .
        /// </summary>
        internal static string OCLParser_CreateIntegerLiteral_Bad_integer_format {
            get {
                return ResourceManager.GetString("OCLParser_CreateIntegerLiteral_Bad_integer_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integer literal `{0}` results in overflow..
        /// </summary>
        internal static string OCLParser_CreateIntegerLiteral_Integer_literal_overflow_1 {
            get {
                return ResourceManager.GetString("OCLParser_CreateIntegerLiteral_Integer_literal_overflow_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong real format..
        /// </summary>
        internal static string OCLParser_CreateRealLiteral_Incorrect_real_format {
            get {
                return ResourceManager.GetString("OCLParser_CreateRealLiteral_Incorrect_real_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name `{0}` is used repeatedly..
        /// </summary>
        internal static string OCLParser_CreateTupleLiteral_Tuple_part_name_used_repeatedly_1 {
            get {
                return ResourceManager.GetString("OCLParser_CreateTupleLiteral_Tuple_part_name_used_repeatedly_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateVariableDeclaration( ... ): missing case for VariableDeclarationRequirement..
        /// </summary>
        internal static string OCLParser_CreateVariableDeclaration_CreateVariableDeclaration_missing_case_for_VariableDeclarationRequirement {
            get {
                return ResourceManager.GetString("OCLParser_CreateVariableDeclaration_CreateVariableDeclaration_missing_case_for_Va" +
                        "riableDeclarationRequirement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loop variables must be initialized. .
        /// </summary>
        internal static string OCLParser_CreateVariableDeclaration_Missing_loop_variable_initialization {
            get {
                return ResourceManager.GetString("OCLParser_CreateVariableDeclaration_Missing_loop_variable_initialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type must be defined and value must be omited for variable declarations of tuple type..
        /// </summary>
        internal static string OCLParser_CreateVariableDeclaration_Of_type_variable_condition {
            get {
                return ResourceManager.GetString("OCLParser_CreateVariableDeclaration_Of_type_variable_condition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type and value must be present in variable declarations for tuple literars..
        /// </summary>
        internal static string OCLParser_CreateVariableDeclaration_tuple_literal_variable_condition {
            get {
                return ResourceManager.GetString("OCLParser_CreateVariableDeclaration_tuple_literal_variable_condition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type `{0}` does not conforms to `{1}`..
        /// </summary>
        internal static string OCLParser_CreateVariableDeclaration_Types_do_not_conform_2 {
            get {
                return ResourceManager.GetString("OCLParser_CreateVariableDeclaration_Types_do_not_conform_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown operation `{1}` on type `{0}`..
        /// </summary>
        internal static string OCLParser_InfixOperation_OperationNotFound_2 {
            get {
                return ResourceManager.GetString("OCLParser_InfixOperation_OperationNotFound_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown operation `{0}`..
        /// </summary>
        internal static string OCLParser_OperationNotFound_1 {
            get {
                return ResourceManager.GetString("OCLParser_OperationNotFound_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable declaration is not allowed here (this is a collection operation, not an iterator expression). .
        /// </summary>
        internal static string OCLParser_ProcessArrowIterator_Illegal_declaration {
            get {
                return ResourceManager.GetString("OCLParser_ProcessArrowIterator_Illegal_declaration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type mismatch..
        /// </summary>
        internal static string OCLParser_ProcessArrowIterator_Type_mismatch {
            get {
                return ResourceManager.GetString("OCLParser_ProcessArrowIterator_Type_mismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorect call convention for iterator..
        /// </summary>
        internal static string OCLParser_PropertyCallBody_IncorectCallConvention {
            get {
                return ResourceManager.GetString("OCLParser_PropertyCallBody_IncorectCallConvention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illegal use of &apos;-&gt;&apos;, source is not a collection..
        /// </summary>
        internal static string OCLParser_PropertyCallBody_SourceOfCollectionOperationIsNotACollection {
            get {
                return ResourceManager.GetString("OCLParser_PropertyCallBody_SourceOfCollectionOperationIsNotACollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier `@pre` is not attached to a variable..
        /// </summary>
        internal static string OCLParser_PropertyCallRoot_PreModifierNotOnVariable {
            get {
                return ResourceManager.GetString("OCLParser_PropertyCallRoot_PreModifierNotOnVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path `{0}` does not refer a type..
        /// </summary>
        internal static string OCLParser_ResolveTypePathName_Path_does_not_refer_a_type_1 {
            get {
                return ResourceManager.GetString("OCLParser_ResolveTypePathName_Path_does_not_refer_a_type_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path `{0}` does not exists..
        /// </summary>
        internal static string OCLParser_ResolveTypePathName_Path_not_exists_1 {
            get {
                return ResourceManager.GetString("OCLParser_ResolveTypePathName_Path_not_exists_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation `{1}` is not defined on type `{0}`..
        /// </summary>
        internal static string OCLParser_UnaryOperation_OperationNotFound_2 {
            get {
                return ResourceManager.GetString("OCLParser_UnaryOperation_OperationNotFound_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unary operation `{1}` is not defined on type `{0}`..
        /// </summary>
        internal static string OCLParser_UnaryOperation_UnaryOperationNotFound {
            get {
                return ResourceManager.GetString("OCLParser_UnaryOperation_UnaryOperationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot decide return type of `{0}`..
        /// </summary>
        internal static string Operation_GetReturnType_1 {
            get {
                return ResourceManager.GetString("Operation_GetReturnType_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable `{0}` has been defined earlier. .
        /// </summary>
        internal static string VariableAlreadyExisted {
            get {
                return ResourceManager.GetString("VariableAlreadyExisted", resourceCulture);
            }
        }
    }
}
