//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exolutio.Model.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Exolutio.Model.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;eXo:Project xmlns:eXo=&quot;http://eXolutio.eu/Project/PIM/built-in-types/&quot;&gt;
        ///  &lt;eXo:AttributeTypes&gt;
        ///    &lt;eXo:AttributeType Name=&quot;Boolean&quot; IsSealed=&quot;True&quot; ID=&quot;1CE3B950-194D-42c9-AEEB-A9CEC5E5505A&quot; /&gt;
        ///    &lt;eXo:AttributeType Name=&quot;Integer&quot; IsSealed=&quot;True&quot; ID=&quot;DC49D35C-FEAF-4e9e-9C22-267208D61A77&quot; /&gt;
        ///    &lt;eXo:AttributeType Name=&quot;Real&quot; IsSealed=&quot;True&quot; ID=&quot;4B229CAA-8808-4bac-9DE1-BC10AA05F6C6&quot; /&gt;
        ///    &lt;eXo:AttributeType Name=&quot;String&quot; IsSealed=&quot;True&quot; ID=&quot;5D84C73E-74CD-4acc- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PIM_built_in_types {
            get {
                return ResourceManager.GetString("PIM_built_in_types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;eXo:Project xmlns:eXo=&quot;http://eXolutio.eu/Project/PSM/built-in-types/&quot;&gt;
        ///  &lt;eXo:AttributeTypes&gt;
        ///    &lt;eXo:AttributeType Name=&quot;duration&quot; IsSealed=&quot;True&quot; ID=&quot;CB7AB121-4845-4175-84F6-06E08B0F21F9&quot; /&gt;
        ///    &lt;eXo:AttributeType Name=&quot;dateTime&quot; IsSealed=&quot;True&quot; ID=&quot;CF33518B-C155-4d3b-B102-AA65954C82B8&quot; /&gt;
        ///    &lt;eXo:AttributeType Name=&quot;time&quot; IsSealed=&quot;True&quot; ID=&quot;1D62B9EE-0763-4a89-90F7-B086868E81F3&quot; /&gt;
        ///    &lt;eXo:AttributeType Name=&quot;date&quot; IsSealed=&quot;True&quot; ID=&quot;BFD5B6AB-988A-429b- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PSM_built_in_types {
            get {
                return ResourceManager.GetString("PSM_built_in_types", resourceCulture);
            }
        }
    }
}
