//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exolutio.View.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Exolutio.View.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;SyntaxDefinition name=&quot;OCL&quot;
        ///        xmlns=&quot;http://icsharpcode.net/sharpdevelop/syntaxdefinition/2008&quot;&gt;
        ///  &lt;Color name=&quot;Comment&quot; foreground=&quot;Green&quot; /&gt;
        ///  &lt;Color name=&quot;String&quot; foreground=&quot;Maroon&quot; /&gt;
        ///  &lt;Color name=&quot;Black&quot; foreground=&quot;Black&quot; fontWeight=&quot;normal&quot; /&gt;
        ///  &lt;Color name=&quot;Message&quot; foreground=&quot;Green&quot; /&gt;
        ///  &lt;Color name=&quot;Keywords&quot; fontWeight=&quot;bold&quot; foreground=&quot;Blue&quot; /&gt;
        ///  
        ///  &lt;!-- This is the main ruleset. --&gt;
        ///  &lt;RuleSet name=&quot;oclMain&quot;&gt;
        ///    &lt;Span color=&quot;Comment&quot; begin=&quot;--&quot; /&gt;
        ///    &lt;Span color=&quot;Comment [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OCL_syntax {
            get {
                return ResourceManager.GetString("OCL_syntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;SyntaxDefinition name=&quot;OCL&quot;
        ///        xmlns=&quot;http://icsharpcode.net/sharpdevelop/syntaxdefinition/2008&quot;&gt;
        ///  &lt;Color name=&quot;Comment&quot; foreground=&quot;Green&quot; /&gt;
        ///  &lt;Color name=&quot;Special&quot; foreground=&quot;Maroon&quot; /&gt;
        ///  &lt;Color name=&quot;Black&quot; foreground=&quot;Black&quot; fontWeight=&quot;normal&quot; /&gt;
        ///  &lt;Color name=&quot;Message&quot; foreground=&quot;Green&quot; /&gt;
        ///  &lt;Color name=&quot;Keywords&quot; fontWeight=&quot;bold&quot; foreground=&quot;Blue&quot; /&gt;
        ///  
        ///  &lt;!-- This is the main ruleset. --&gt;
        ///  &lt;RuleSet&gt;
        ///    &lt;Span color=&quot;Comment&quot; begin=&quot;#&quot; /&gt;
        ///    
        ///    &lt;Keywords color=&quot;Keywords&quot;&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RNC {
            get {
                return ResourceManager.GetString("RNC", resourceCulture);
            }
        }
    }
}
