//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exolutio.View.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Exolutio.View.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xquery version &apos;3.0&apos;;
        ///
        ///module namespace music-forms = &quot;http://jakubmaly.cz/music/forms&quot;;
        ///
        ///import module namespace music-rest = &quot;http://jakubmaly.cz/music/rest&quot; at &quot;music-rest.xqm&quot;;
        ///
        ///declare namespace xs = &quot;http://www.w3.org/2001/XMLSchema&quot;; 
        ///declare variable $music-forms:restxq := &apos;http://localhost:8080/exist/restxq&apos;;
        ///
        ///declare function music-forms:create-form-view-Artist($ID as xs:integer?)
        ///{
        ///&lt;div xmlns:ev=&quot;http://www.w3.org/2001/xml-events&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xf=&quot;h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string music_xrx_forms {
            get {
                return ResourceManager.GetString("music-xrx-forms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xquery version &quot;3.0&quot;;
        ///
        ///module namespace music-rest = &quot;http://jakubmaly.cz/music/rest&quot;;
        ///declare namespace music = &quot;http://jakubmaly.cz/music&quot;;
        ///import module namespace functx = &quot;http://www.functx.com&quot; at &quot;functx.xqm&quot;;
        ///(: import module namespace music = &quot;http://jakubmaly.cz/music&quot; at &apos;ruian-lib.xqm&apos;; :)
        ///
        ///declare namespace rest=&quot;http://exquery.org/ns/restxq&quot;;
        ///declare namespace req=&quot;http://exquery.org/ns/request&quot;;
        ///declare namespace http = &quot;http://expath.org/ns/http-client&quot;;
        ///declare namespace xs=&quot;http://www.w3.or [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string music_xrx_rest {
            get {
                return ResourceManager.GetString("music-xrx-rest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;SyntaxDefinition name=&quot;OCL&quot;
        ///        xmlns=&quot;http://icsharpcode.net/sharpdevelop/syntaxdefinition/2008&quot;&gt;
        ///  &lt;Color name=&quot;Comment&quot; foreground=&quot;Green&quot; /&gt;
        ///  &lt;Color name=&quot;String&quot; foreground=&quot;Maroon&quot; /&gt;
        ///  &lt;Color name=&quot;Black&quot; foreground=&quot;Black&quot; fontWeight=&quot;normal&quot; /&gt;
        ///  &lt;Color name=&quot;Message&quot; foreground=&quot;Green&quot; /&gt;
        ///  &lt;Color name=&quot;Keywords&quot; fontWeight=&quot;bold&quot; foreground=&quot;Blue&quot; /&gt;
        ///  
        ///  &lt;!-- This is the main ruleset. --&gt;
        ///  &lt;RuleSet name=&quot;oclMain&quot;&gt;
        ///    &lt;Span color=&quot;Comment&quot; begin=&quot;--&quot; /&gt;
        ///    &lt;Span color=&quot;Comment [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OCL_syntax {
            get {
                return ResourceManager.GetString("OCL_syntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;SyntaxDefinition name=&quot;RNC&quot;
        ///        xmlns=&quot;http://icsharpcode.net/sharpdevelop/syntaxdefinition/2008&quot;&gt;
        ///  &lt;Color name=&quot;Comment&quot; foreground=&quot;Green&quot; /&gt;
        ///  &lt;Color name=&quot;Special&quot; foreground=&quot;Maroon&quot; /&gt;
        ///  &lt;Color name=&quot;Black&quot; foreground=&quot;Black&quot; fontWeight=&quot;normal&quot; /&gt;
        ///  &lt;Color name=&quot;Message&quot; foreground=&quot;Green&quot; /&gt;
        ///  &lt;Color name=&quot;Keywords&quot; fontWeight=&quot;bold&quot; foreground=&quot;Blue&quot; /&gt;
        ///  
        ///  &lt;!-- This is the main ruleset. --&gt;
        ///  &lt;RuleSet&gt;
        ///    &lt;Span color=&quot;Comment&quot; begin=&quot;#&quot; /&gt;
        ///    
        ///    &lt;Keywords color=&quot;Keywords&quot;&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RNC {
            get {
                return ResourceManager.GetString("RNC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;SyntaxDefinition name=&quot;RNC&quot;
        ///        xmlns=&quot;http://icsharpcode.net/sharpdevelop/syntaxdefinition/2008&quot;&gt;
        ///  &lt;Color name=&quot;Comment&quot; foreground=&quot;Green&quot; /&gt;
        ///  &lt;Color name=&quot;Special&quot; foreground=&quot;Maroon&quot; /&gt;
        ///  &lt;Color name=&quot;String&quot; foreground=&quot;Maroon&quot; /&gt;
        ///  &lt;Color name=&quot;Black&quot; foreground=&quot;Black&quot; fontWeight=&quot;normal&quot; /&gt;
        ///  &lt;Color name=&quot;Message&quot; foreground=&quot;Green&quot; /&gt;
        ///  &lt;Color name=&quot;Keywords&quot; fontWeight=&quot;bold&quot; foreground=&quot;Blue&quot; /&gt;
        ///  
        ///  &lt;!-- This is the main ruleset. --&gt;
        ///  &lt;RuleSet&gt;
        ///    &lt;Span color=&quot;Comment&quot; begin= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XQuery {
            get {
                return ResourceManager.GetString("XQuery", resourceCulture);
            }
        }
    }
}
