//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvoX.Updater.UpdaterService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Version", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Version : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FileWithVersion", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class FileWithVersion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VersionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string File {
            get {
                return this.FileField;
            }
            set {
                if ((object.ReferenceEquals(this.FileField, value) != true)) {
                    this.FileField = value;
                    this.RaisePropertyChanged("File");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Version {
            get {
                return this.VersionField;
            }
            set {
                if ((object.ReferenceEquals(this.VersionField, value) != true)) {
                    this.VersionField = value;
                    this.RaisePropertyChanged("Version");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UpdaterService.UpdaterServiceSoap")]
    public interface UpdaterServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        EvoX.Updater.UpdaterService.HelloWorldResponse HelloWorld(EvoX.Updater.UpdaterService.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name GetVersionResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetVersion", ReplyAction="*")]
        EvoX.Updater.UpdaterService.GetVersionResponse GetVersion(EvoX.Updater.UpdaterService.GetVersionRequest request);
        
        // CODEGEN: Generating message contract since element name files from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetVersions", ReplyAction="*")]
        EvoX.Updater.UpdaterService.GetVersionsResponse GetVersions(EvoX.Updater.UpdaterService.GetVersionsRequest request);
        
        // CODEGEN: Generating message contract since element name files from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MustReinstal", ReplyAction="*")]
        EvoX.Updater.UpdaterService.MustReinstalResponse MustReinstal(EvoX.Updater.UpdaterService.MustReinstalRequest request);
        
        // CODEGEN: Generating message contract since element name GetMsiUriResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMsiUri", ReplyAction="*")]
        EvoX.Updater.UpdaterService.GetMsiUriResponse GetMsiUri(EvoX.Updater.UpdaterService.GetMsiUriRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public EvoX.Updater.UpdaterService.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(EvoX.Updater.UpdaterService.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public EvoX.Updater.UpdaterService.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(EvoX.Updater.UpdaterService.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetVersionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetVersion", Namespace="http://tempuri.org/", Order=0)]
        public EvoX.Updater.UpdaterService.GetVersionRequestBody Body;
        
        public GetVersionRequest() {
        }
        
        public GetVersionRequest(EvoX.Updater.UpdaterService.GetVersionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetVersionRequestBody {
        
        public GetVersionRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetVersionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetVersionResponse", Namespace="http://tempuri.org/", Order=0)]
        public EvoX.Updater.UpdaterService.GetVersionResponseBody Body;
        
        public GetVersionResponse() {
        }
        
        public GetVersionResponse(EvoX.Updater.UpdaterService.GetVersionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetVersionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public EvoX.Updater.UpdaterService.Version GetVersionResult;
        
        public GetVersionResponseBody() {
        }
        
        public GetVersionResponseBody(EvoX.Updater.UpdaterService.Version GetVersionResult) {
            this.GetVersionResult = GetVersionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetVersionsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetVersions", Namespace="http://tempuri.org/", Order=0)]
        public EvoX.Updater.UpdaterService.GetVersionsRequestBody Body;
        
        public GetVersionsRequest() {
        }
        
        public GetVersionsRequest(EvoX.Updater.UpdaterService.GetVersionsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetVersionsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public EvoX.Updater.UpdaterService.ArrayOfString files;
        
        public GetVersionsRequestBody() {
        }
        
        public GetVersionsRequestBody(EvoX.Updater.UpdaterService.ArrayOfString files) {
            this.files = files;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetVersionsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetVersionsResponse", Namespace="http://tempuri.org/", Order=0)]
        public EvoX.Updater.UpdaterService.GetVersionsResponseBody Body;
        
        public GetVersionsResponse() {
        }
        
        public GetVersionsResponse(EvoX.Updater.UpdaterService.GetVersionsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetVersionsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public EvoX.Updater.UpdaterService.FileWithVersion[] GetVersionsResult;
        
        public GetVersionsResponseBody() {
        }
        
        public GetVersionsResponseBody(EvoX.Updater.UpdaterService.FileWithVersion[] GetVersionsResult) {
            this.GetVersionsResult = GetVersionsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MustReinstalRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MustReinstal", Namespace="http://tempuri.org/", Order=0)]
        public EvoX.Updater.UpdaterService.MustReinstalRequestBody Body;
        
        public MustReinstalRequest() {
        }
        
        public MustReinstalRequest(EvoX.Updater.UpdaterService.MustReinstalRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MustReinstalRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public EvoX.Updater.UpdaterService.ArrayOfString files;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public EvoX.Updater.UpdaterService.ArrayOfString versions;
        
        public MustReinstalRequestBody() {
        }
        
        public MustReinstalRequestBody(EvoX.Updater.UpdaterService.ArrayOfString files, EvoX.Updater.UpdaterService.ArrayOfString versions) {
            this.files = files;
            this.versions = versions;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MustReinstalResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MustReinstalResponse", Namespace="http://tempuri.org/", Order=0)]
        public EvoX.Updater.UpdaterService.MustReinstalResponseBody Body;
        
        public MustReinstalResponse() {
        }
        
        public MustReinstalResponse(EvoX.Updater.UpdaterService.MustReinstalResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MustReinstalResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool MustReinstalResult;
        
        public MustReinstalResponseBody() {
        }
        
        public MustReinstalResponseBody(bool MustReinstalResult) {
            this.MustReinstalResult = MustReinstalResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMsiUriRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMsiUri", Namespace="http://tempuri.org/", Order=0)]
        public EvoX.Updater.UpdaterService.GetMsiUriRequestBody Body;
        
        public GetMsiUriRequest() {
        }
        
        public GetMsiUriRequest(EvoX.Updater.UpdaterService.GetMsiUriRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetMsiUriRequestBody {
        
        public GetMsiUriRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMsiUriResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMsiUriResponse", Namespace="http://tempuri.org/", Order=0)]
        public EvoX.Updater.UpdaterService.GetMsiUriResponseBody Body;
        
        public GetMsiUriResponse() {
        }
        
        public GetMsiUriResponse(EvoX.Updater.UpdaterService.GetMsiUriResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMsiUriResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetMsiUriResult;
        
        public GetMsiUriResponseBody() {
        }
        
        public GetMsiUriResponseBody(string GetMsiUriResult) {
            this.GetMsiUriResult = GetMsiUriResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UpdaterServiceSoapChannel : EvoX.Updater.UpdaterService.UpdaterServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UpdaterServiceSoapClient : System.ServiceModel.ClientBase<EvoX.Updater.UpdaterService.UpdaterServiceSoap>, EvoX.Updater.UpdaterService.UpdaterServiceSoap {
        
        public UpdaterServiceSoapClient() {
        }
        
        public UpdaterServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UpdaterServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UpdaterServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UpdaterServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EvoX.Updater.UpdaterService.HelloWorldResponse EvoX.Updater.UpdaterService.UpdaterServiceSoap.HelloWorld(EvoX.Updater.UpdaterService.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            EvoX.Updater.UpdaterService.HelloWorldRequest inValue = new EvoX.Updater.UpdaterService.HelloWorldRequest();
            inValue.Body = new EvoX.Updater.UpdaterService.HelloWorldRequestBody();
            EvoX.Updater.UpdaterService.HelloWorldResponse retVal = ((EvoX.Updater.UpdaterService.UpdaterServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EvoX.Updater.UpdaterService.GetVersionResponse EvoX.Updater.UpdaterService.UpdaterServiceSoap.GetVersion(EvoX.Updater.UpdaterService.GetVersionRequest request) {
            return base.Channel.GetVersion(request);
        }
        
        public EvoX.Updater.UpdaterService.Version GetVersion() {
            EvoX.Updater.UpdaterService.GetVersionRequest inValue = new EvoX.Updater.UpdaterService.GetVersionRequest();
            inValue.Body = new EvoX.Updater.UpdaterService.GetVersionRequestBody();
            EvoX.Updater.UpdaterService.GetVersionResponse retVal = ((EvoX.Updater.UpdaterService.UpdaterServiceSoap)(this)).GetVersion(inValue);
            return retVal.Body.GetVersionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EvoX.Updater.UpdaterService.GetVersionsResponse EvoX.Updater.UpdaterService.UpdaterServiceSoap.GetVersions(EvoX.Updater.UpdaterService.GetVersionsRequest request) {
            return base.Channel.GetVersions(request);
        }
        
        public EvoX.Updater.UpdaterService.FileWithVersion[] GetVersions(EvoX.Updater.UpdaterService.ArrayOfString files) {
            EvoX.Updater.UpdaterService.GetVersionsRequest inValue = new EvoX.Updater.UpdaterService.GetVersionsRequest();
            inValue.Body = new EvoX.Updater.UpdaterService.GetVersionsRequestBody();
            inValue.Body.files = files;
            EvoX.Updater.UpdaterService.GetVersionsResponse retVal = ((EvoX.Updater.UpdaterService.UpdaterServiceSoap)(this)).GetVersions(inValue);
            return retVal.Body.GetVersionsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EvoX.Updater.UpdaterService.MustReinstalResponse EvoX.Updater.UpdaterService.UpdaterServiceSoap.MustReinstal(EvoX.Updater.UpdaterService.MustReinstalRequest request) {
            return base.Channel.MustReinstal(request);
        }
        
        public bool MustReinstal(EvoX.Updater.UpdaterService.ArrayOfString files, EvoX.Updater.UpdaterService.ArrayOfString versions) {
            EvoX.Updater.UpdaterService.MustReinstalRequest inValue = new EvoX.Updater.UpdaterService.MustReinstalRequest();
            inValue.Body = new EvoX.Updater.UpdaterService.MustReinstalRequestBody();
            inValue.Body.files = files;
            inValue.Body.versions = versions;
            EvoX.Updater.UpdaterService.MustReinstalResponse retVal = ((EvoX.Updater.UpdaterService.UpdaterServiceSoap)(this)).MustReinstal(inValue);
            return retVal.Body.MustReinstalResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EvoX.Updater.UpdaterService.GetMsiUriResponse EvoX.Updater.UpdaterService.UpdaterServiceSoap.GetMsiUri(EvoX.Updater.UpdaterService.GetMsiUriRequest request) {
            return base.Channel.GetMsiUri(request);
        }
        
        public string GetMsiUri() {
            EvoX.Updater.UpdaterService.GetMsiUriRequest inValue = new EvoX.Updater.UpdaterService.GetMsiUriRequest();
            inValue.Body = new EvoX.Updater.UpdaterService.GetMsiUriRequestBody();
            EvoX.Updater.UpdaterService.GetMsiUriResponse retVal = ((EvoX.Updater.UpdaterService.UpdaterServiceSoap)(this)).GetMsiUri(inValue);
            return retVal.Body.GetMsiUriResult;
        }
    }
}
