//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exolutio.Updater.UpdaterService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Version", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Version : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FileWithVersion", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class FileWithVersion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VersionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string File {
            get {
                return this.FileField;
            }
            set {
                if ((object.ReferenceEquals(this.FileField, value) != true)) {
                    this.FileField = value;
                    this.RaisePropertyChanged("File");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Version {
            get {
                return this.VersionField;
            }
            set {
                if ((object.ReferenceEquals(this.VersionField, value) != true)) {
                    this.VersionField = value;
                    this.RaisePropertyChanged("Version");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UpdaterService.UpdaterServiceSoap")]
    public interface UpdaterServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        Exolutio.Updater.UpdaterService.HelloWorldResponse HelloWorld(Exolutio.Updater.UpdaterService.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name GetExeVersionResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetExeVersion", ReplyAction="*")]
        Exolutio.Updater.UpdaterService.GetExeVersionResponse GetExeVersion(Exolutio.Updater.UpdaterService.GetExeVersionRequest request);
        
        // CODEGEN: Generating message contract since element name file from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetVersion", ReplyAction="*")]
        Exolutio.Updater.UpdaterService.GetVersionResponse GetVersion(Exolutio.Updater.UpdaterService.GetVersionRequest request);
        
        // CODEGEN: Generating message contract since element name files from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetVersions", ReplyAction="*")]
        Exolutio.Updater.UpdaterService.GetVersionsResponse GetVersions(Exolutio.Updater.UpdaterService.GetVersionsRequest request);
        
        // CODEGEN: Generating message contract since element name files from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MustReinstal", ReplyAction="*")]
        Exolutio.Updater.UpdaterService.MustReinstalResponse MustReinstal(Exolutio.Updater.UpdaterService.MustReinstalRequest request);
        
        // CODEGEN: Generating message contract since element name GetMsiUriResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMsiUri", ReplyAction="*")]
        Exolutio.Updater.UpdaterService.GetMsiUriResponse GetMsiUri(Exolutio.Updater.UpdaterService.GetMsiUriRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public Exolutio.Updater.UpdaterService.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(Exolutio.Updater.UpdaterService.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public Exolutio.Updater.UpdaterService.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(Exolutio.Updater.UpdaterService.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetExeVersionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetExeVersion", Namespace="http://tempuri.org/", Order=0)]
        public Exolutio.Updater.UpdaterService.GetExeVersionRequestBody Body;
        
        public GetExeVersionRequest() {
        }
        
        public GetExeVersionRequest(Exolutio.Updater.UpdaterService.GetExeVersionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetExeVersionRequestBody {
        
        public GetExeVersionRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetExeVersionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetExeVersionResponse", Namespace="http://tempuri.org/", Order=0)]
        public Exolutio.Updater.UpdaterService.GetExeVersionResponseBody Body;
        
        public GetExeVersionResponse() {
        }
        
        public GetExeVersionResponse(Exolutio.Updater.UpdaterService.GetExeVersionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetExeVersionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Exolutio.Updater.UpdaterService.Version GetExeVersionResult;
        
        public GetExeVersionResponseBody() {
        }
        
        public GetExeVersionResponseBody(Exolutio.Updater.UpdaterService.Version GetExeVersionResult) {
            this.GetExeVersionResult = GetExeVersionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetVersionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetVersion", Namespace="http://tempuri.org/", Order=0)]
        public Exolutio.Updater.UpdaterService.GetVersionRequestBody Body;
        
        public GetVersionRequest() {
        }
        
        public GetVersionRequest(Exolutio.Updater.UpdaterService.GetVersionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetVersionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string file;
        
        public GetVersionRequestBody() {
        }
        
        public GetVersionRequestBody(string file) {
            this.file = file;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetVersionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetVersionResponse", Namespace="http://tempuri.org/", Order=0)]
        public Exolutio.Updater.UpdaterService.GetVersionResponseBody Body;
        
        public GetVersionResponse() {
        }
        
        public GetVersionResponse(Exolutio.Updater.UpdaterService.GetVersionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetVersionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Exolutio.Updater.UpdaterService.Version GetVersionResult;
        
        public GetVersionResponseBody() {
        }
        
        public GetVersionResponseBody(Exolutio.Updater.UpdaterService.Version GetVersionResult) {
            this.GetVersionResult = GetVersionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetVersionsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetVersions", Namespace="http://tempuri.org/", Order=0)]
        public Exolutio.Updater.UpdaterService.GetVersionsRequestBody Body;
        
        public GetVersionsRequest() {
        }
        
        public GetVersionsRequest(Exolutio.Updater.UpdaterService.GetVersionsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetVersionsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Exolutio.Updater.UpdaterService.ArrayOfString files;
        
        public GetVersionsRequestBody() {
        }
        
        public GetVersionsRequestBody(Exolutio.Updater.UpdaterService.ArrayOfString files) {
            this.files = files;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetVersionsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetVersionsResponse", Namespace="http://tempuri.org/", Order=0)]
        public Exolutio.Updater.UpdaterService.GetVersionsResponseBody Body;
        
        public GetVersionsResponse() {
        }
        
        public GetVersionsResponse(Exolutio.Updater.UpdaterService.GetVersionsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetVersionsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Exolutio.Updater.UpdaterService.FileWithVersion[] GetVersionsResult;
        
        public GetVersionsResponseBody() {
        }
        
        public GetVersionsResponseBody(Exolutio.Updater.UpdaterService.FileWithVersion[] GetVersionsResult) {
            this.GetVersionsResult = GetVersionsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MustReinstalRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MustReinstal", Namespace="http://tempuri.org/", Order=0)]
        public Exolutio.Updater.UpdaterService.MustReinstalRequestBody Body;
        
        public MustReinstalRequest() {
        }
        
        public MustReinstalRequest(Exolutio.Updater.UpdaterService.MustReinstalRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MustReinstalRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Exolutio.Updater.UpdaterService.ArrayOfString files;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public Exolutio.Updater.UpdaterService.ArrayOfString versions;
        
        public MustReinstalRequestBody() {
        }
        
        public MustReinstalRequestBody(Exolutio.Updater.UpdaterService.ArrayOfString files, Exolutio.Updater.UpdaterService.ArrayOfString versions) {
            this.files = files;
            this.versions = versions;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MustReinstalResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MustReinstalResponse", Namespace="http://tempuri.org/", Order=0)]
        public Exolutio.Updater.UpdaterService.MustReinstalResponseBody Body;
        
        public MustReinstalResponse() {
        }
        
        public MustReinstalResponse(Exolutio.Updater.UpdaterService.MustReinstalResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MustReinstalResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool MustReinstalResult;
        
        public MustReinstalResponseBody() {
        }
        
        public MustReinstalResponseBody(bool MustReinstalResult) {
            this.MustReinstalResult = MustReinstalResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMsiUriRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMsiUri", Namespace="http://tempuri.org/", Order=0)]
        public Exolutio.Updater.UpdaterService.GetMsiUriRequestBody Body;
        
        public GetMsiUriRequest() {
        }
        
        public GetMsiUriRequest(Exolutio.Updater.UpdaterService.GetMsiUriRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetMsiUriRequestBody {
        
        public GetMsiUriRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMsiUriResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMsiUriResponse", Namespace="http://tempuri.org/", Order=0)]
        public Exolutio.Updater.UpdaterService.GetMsiUriResponseBody Body;
        
        public GetMsiUriResponse() {
        }
        
        public GetMsiUriResponse(Exolutio.Updater.UpdaterService.GetMsiUriResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMsiUriResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetMsiUriResult;
        
        public GetMsiUriResponseBody() {
        }
        
        public GetMsiUriResponseBody(string GetMsiUriResult) {
            this.GetMsiUriResult = GetMsiUriResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UpdaterServiceSoapChannel : Exolutio.Updater.UpdaterService.UpdaterServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UpdaterServiceSoapClient : System.ServiceModel.ClientBase<Exolutio.Updater.UpdaterService.UpdaterServiceSoap>, Exolutio.Updater.UpdaterService.UpdaterServiceSoap {
        
        public UpdaterServiceSoapClient() {
        }
        
        public UpdaterServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UpdaterServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UpdaterServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UpdaterServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Exolutio.Updater.UpdaterService.HelloWorldResponse Exolutio.Updater.UpdaterService.UpdaterServiceSoap.HelloWorld(Exolutio.Updater.UpdaterService.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            Exolutio.Updater.UpdaterService.HelloWorldRequest inValue = new Exolutio.Updater.UpdaterService.HelloWorldRequest();
            inValue.Body = new Exolutio.Updater.UpdaterService.HelloWorldRequestBody();
            Exolutio.Updater.UpdaterService.HelloWorldResponse retVal = ((Exolutio.Updater.UpdaterService.UpdaterServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Exolutio.Updater.UpdaterService.GetExeVersionResponse Exolutio.Updater.UpdaterService.UpdaterServiceSoap.GetExeVersion(Exolutio.Updater.UpdaterService.GetExeVersionRequest request) {
            return base.Channel.GetExeVersion(request);
        }
        
        public Exolutio.Updater.UpdaterService.Version GetExeVersion() {
            Exolutio.Updater.UpdaterService.GetExeVersionRequest inValue = new Exolutio.Updater.UpdaterService.GetExeVersionRequest();
            inValue.Body = new Exolutio.Updater.UpdaterService.GetExeVersionRequestBody();
            Exolutio.Updater.UpdaterService.GetExeVersionResponse retVal = ((Exolutio.Updater.UpdaterService.UpdaterServiceSoap)(this)).GetExeVersion(inValue);
            return retVal.Body.GetExeVersionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Exolutio.Updater.UpdaterService.GetVersionResponse Exolutio.Updater.UpdaterService.UpdaterServiceSoap.GetVersion(Exolutio.Updater.UpdaterService.GetVersionRequest request) {
            return base.Channel.GetVersion(request);
        }
        
        public Exolutio.Updater.UpdaterService.Version GetVersion(string file) {
            Exolutio.Updater.UpdaterService.GetVersionRequest inValue = new Exolutio.Updater.UpdaterService.GetVersionRequest();
            inValue.Body = new Exolutio.Updater.UpdaterService.GetVersionRequestBody();
            inValue.Body.file = file;
            Exolutio.Updater.UpdaterService.GetVersionResponse retVal = ((Exolutio.Updater.UpdaterService.UpdaterServiceSoap)(this)).GetVersion(inValue);
            return retVal.Body.GetVersionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Exolutio.Updater.UpdaterService.GetVersionsResponse Exolutio.Updater.UpdaterService.UpdaterServiceSoap.GetVersions(Exolutio.Updater.UpdaterService.GetVersionsRequest request) {
            return base.Channel.GetVersions(request);
        }
        
        public Exolutio.Updater.UpdaterService.FileWithVersion[] GetVersions(Exolutio.Updater.UpdaterService.ArrayOfString files) {
            Exolutio.Updater.UpdaterService.GetVersionsRequest inValue = new Exolutio.Updater.UpdaterService.GetVersionsRequest();
            inValue.Body = new Exolutio.Updater.UpdaterService.GetVersionsRequestBody();
            inValue.Body.files = files;
            Exolutio.Updater.UpdaterService.GetVersionsResponse retVal = ((Exolutio.Updater.UpdaterService.UpdaterServiceSoap)(this)).GetVersions(inValue);
            return retVal.Body.GetVersionsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Exolutio.Updater.UpdaterService.MustReinstalResponse Exolutio.Updater.UpdaterService.UpdaterServiceSoap.MustReinstal(Exolutio.Updater.UpdaterService.MustReinstalRequest request) {
            return base.Channel.MustReinstal(request);
        }
        
        public bool MustReinstal(Exolutio.Updater.UpdaterService.ArrayOfString files, Exolutio.Updater.UpdaterService.ArrayOfString versions) {
            Exolutio.Updater.UpdaterService.MustReinstalRequest inValue = new Exolutio.Updater.UpdaterService.MustReinstalRequest();
            inValue.Body = new Exolutio.Updater.UpdaterService.MustReinstalRequestBody();
            inValue.Body.files = files;
            inValue.Body.versions = versions;
            Exolutio.Updater.UpdaterService.MustReinstalResponse retVal = ((Exolutio.Updater.UpdaterService.UpdaterServiceSoap)(this)).MustReinstal(inValue);
            return retVal.Body.MustReinstalResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Exolutio.Updater.UpdaterService.GetMsiUriResponse Exolutio.Updater.UpdaterService.UpdaterServiceSoap.GetMsiUri(Exolutio.Updater.UpdaterService.GetMsiUriRequest request) {
            return base.Channel.GetMsiUri(request);
        }
        
        public string GetMsiUri() {
            Exolutio.Updater.UpdaterService.GetMsiUriRequest inValue = new Exolutio.Updater.UpdaterService.GetMsiUriRequest();
            inValue.Body = new Exolutio.Updater.UpdaterService.GetMsiUriRequestBody();
            Exolutio.Updater.UpdaterService.GetMsiUriResponse retVal = ((Exolutio.Updater.UpdaterService.UpdaterServiceSoap)(this)).GetMsiUri(inValue);
            return retVal.Body.GetMsiUriResult;
        }
    }
}
